// <auto-generated />
namespace VMS.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_field_added_to_visitors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_field_added_to_visitors));
        
        string IMigrationMetadata.Id
        {
            get { return "201508241118455_new_field_added_to_visitors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
