// <auto-generated />
namespace VMS.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addednewfieldVisitorPictovisitor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addednewfieldVisitorPictovisitor));
        
        string IMigrationMetadata.Id
        {
            get { return "201508260655583_added new field VisitorPic to visitor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
